name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir_version: 1.16.3
            otp_version: 26.2.5
            lint: true
          - elixir_version: 1.14.5
            otp_version: 25.3.2.12
            blend: nx_0_6
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp_version}}
          elixir-version: ${{matrix.elixir_version}}
      - run: cp blend/${{matrix.blend}}.mix.lock mix.lock
        if: matrix.blend
      - run: mix deps.get
      - run: mix format --check-formatted
        if: ${{ matrix.lint }}
      - run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}
      - run: mix deps.compile
      - run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}
      - run: mix test
